### ISSUE TITLE
Merge apks error, seems like androidx lib & com.google.android.material error.

### ISSUE THREAD

**Issue by hwangjr** [FoelliX/AMT#4]
Here is the log:
```
java -jar AMT.jar todo.apk HelloWorld.apk
09/28/2021 - 11:11:56 AMT-Log> AMT started! (Merging 2 apps)
	1. /Users/x/xx/xxx/todo.apk
	2. /Users/x/xx/xxx/HelloWorld.apk


09/28/2021 - 11:11:56 AMT-Log> *** Step 1/5: Parsing Manifest ***
09/28/2021 - 11:11:56 AMT-Log> successful!


09/28/2021 - 11:11:56 AMT-Log> *** Step 2/5: Parsing Apps ***
09/28/2021 - 11:12:08 AMT-Log> successful!


09/28/2021 - 11:12:08 AMT-Log> *** Step 3/5: Instrumenting Classes ***
09/28/2021 - 11:12:16 AMT-Log> successful!


09/28/2021 - 11:12:16 AMT-Log> *** Step 4/5: Building Merged App ***
09/28/2021 - 11:12:20 AMT-Log> Writing APK!
09/28/2021 - 11:12:24 AMT-Log> Class "com.google.android.material.button.MaterialButtonHelper" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "androidx.print.PrintHelper$PrintUriAdapter$1" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "androidx.print.PrintHelper$PrintBitmapAdapter" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "androidx.print.PrintHelper$PrintUriAdapter" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "androidx.constraintlayout.motion.widget.MotionPaths" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "com.google.android.material.textfield.DropdownMenuEndIconDelegate" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "androidx.appcompat.widget.ScrollingTabContainerView$TabView" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "com.google.android.material.shape.MaterialShapeDrawable" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "com.google.android.material.internal.CheckableImageButton_6" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "androidx.core.view.accessibility.AccessibilityNodeInfoCompat" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "androidx.appcompat.graphics.drawable.DrawerArrowDrawable" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "androidx.navigation.NavDeepLink" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "androidx.transition.TransitionUtils" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "androidx.recyclerview.widget.GridLayoutManager_9" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "com.google.android.material.textfield.ClearTextEndIconDelegate$2" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "androidx.core.view.ViewCompat" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "androidx.core.view.ViewCompat$5" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "androidx.core.view.ViewCompat$3" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "androidx.core.view.ViewCompat$4" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:24 AMT-Log> Class "androidx.core.view.ViewCompat$AccessibilityViewProperty" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:25 AMT-Log> Class "androidx.core.app.NotificationCompatJellybean" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:26 AMT-Log> Class "com.google.android.material.slider.BaseSlider" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:26 AMT-Log> Class "androidx.appcompat.widget.ActivityChooserModel" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:26 AMT-Log> Class "com.google.android.material.appbar.AppBarLayout_16" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:26 AMT-Log> Class "com.google.android.material.appbar.AppBarLayout_16$ScrollingViewBehavior" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:26 AMT-Log> Class "com.google.android.material.textfield.PasswordToggleEndIconDelegate$1" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:26 AMT-Log> Class "com.google.android.material.textfield.PasswordToggleEndIconDelegate$2" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:26 AMT-Log> Class "androidx.constraintlayout.solver.widgets.ConstraintWidget" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:26 AMT-Log> Class "androidx.constraintlayout.motion.widget.MotionLayout" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:27 AMT-Log> Class "androidx.fragment.app.Fragment" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:27 AMT-Log> Class "androidx.recyclerview.widget.RecyclerView_20" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:27 AMT-Log> Class "androidx.recyclerview.widget.RecyclerView_20$AdapterDataObservable" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:27 AMT-Log> Class "androidx.appcompat.app.AlertController_22" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:27 AMT-Log> Class "androidx.appcompat.widget.AppCompatTextViewAutoSizeHelper" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:27 AMT-Log> Class "androidx.appcompat.view.menu.ActionMenuItemView_26" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:27 AMT-Log> Class "androidx.constraintlayout.motion.widget.TimeCycleSplineSet$CustomSet" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "androidx.appcompat.widget.SearchView_28" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "com.google.android.material.appbar.CollapsingToolbarLayout" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "com.google.android.material.card.MaterialCardView" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "androidx.loader.content.Loader" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "com.google.android.material.textfield.TextInputLayout$AccessibilityDelegate" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "com.google.android.material.textfield.TextInputLayout$1" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "androidx.appcompat.widget.ActionMenuView_32" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "androidx.appcompat.graphics.drawable.AnimatedStateListDrawableCompat" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "androidx.fragment.app.FragmentStateManager" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "com.google.android.material.internal.ForegroundLinearLayout" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "androidx.documentfile.provider.RawDocumentFile" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "androidx.core.graphics.PaintCompat" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "androidx.recyclerview.widget.StaggeredGridLayoutManager_37" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "androidx.fragment.app.FragmentManagerViewModel" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "com.google.android.material.tabs.TabLayout$TabView" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "androidx.transition.Transition" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "androidx.recyclerview.widget.SortedList" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "androidx.collection.ArraySet" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "androidx.coordinatorlayout.widget.CoordinatorLayout_41" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "androidx.coordinatorlayout.widget.CoordinatorLayout_41$LayoutParams" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "com.google.android.material.textfield.TextInputEditText" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:28 AMT-Log> Class "androidx.constraintlayout.motion.widget.MotionConstrainedPoint" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "com.google.android.material.button.MaterialButton" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "androidx.transition.TransitionSet" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "androidx.appcompat.widget.ListPopupWindow" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "androidx.recyclerview.widget.LinearLayoutManager_45" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "androidx.constraintlayout.solver.widgets.analyzer.DependencyGraph" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "androidx.core.widget.NestedScrollView_47" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "androidx.vectordrawable.graphics.drawable.VectorDrawableCompat$VectorDrawableCompatState" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "androidx.vectordrawable.graphics.drawable.VectorDrawableCompat$VGroup" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "androidx.vectordrawable.graphics.drawable.VectorDrawableCompat$VFullPath" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "androidx.constraintlayout.motion.widget.MotionController" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "androidx.recyclerview.widget.ItemTouchHelper" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "com.google.android.material.bottomsheet.BottomSheetBehavior_48" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "androidx.appcompat.view.menu.MenuBuilder" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "com.google.android.material.timepicker.ClockHandView" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "androidx.drawerlayout.widget.DrawerLayout_51" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "androidx.fragment.app.FragmentAnim$EndViewTransitionAnimation" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "com.google.android.material.textfield.CutoutDrawable" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "androidx.appcompat.app.AppCompatDelegateImpl" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "androidx.constraintlayout.motion.widget.MotionScene$Transition" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "androidx.appcompat.widget.ActionMenuPresenter" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:29 AMT-Log> Class "androidx.fragment.app.FragmentManager" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:30 AMT-Log> Class "androidx.appcompat.view.ActionBarPolicy" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:30 AMT-Log> Class "androidx.recyclerview.widget.DefaultItemAnimator" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:30 AMT-Log> Class "androidx.appcompat.widget.ActionBarContextView_54" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:30 AMT-Log> Class "com.google.android.material.chip.ChipDrawable" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:30 AMT-Log> Class "androidx.core.widget.TextViewCompat$OreoCallback" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:30 AMT-Log> Class "com.google.android.material.card.MaterialCardViewHelper" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:30 AMT-Log> Class "androidx.viewpager.widget.ViewPager_56" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:30 AMT-Log> Class "androidx.appcompat.widget.SwitchCompat" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:30 AMT-Log> Class "androidx.fragment.app.FragmentActivity" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:30 AMT-Log> Class "androidx.fragment.app.FragmentActivity$HostCallbacks" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:30 AMT-Log> Class "androidx.core.view.GestureDetectorCompat$GestureDetectorCompatImplBase" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:30 AMT-Log> Class "androidx.core.view.WindowInsetsCompat" could not be written to APK. Reason: Invalid code contained! (RuntimeException: not found: unknown)
09/28/2021 - 11:12:33 AMT-Log> successful!


09/28/2021 - 11:12:33 AMT-Log> *** Step 5/5: Run Apktool (Merge Manifests) ***
09/28/2021 - 11:12:57 AMT-Log> File could not be moved from /Users/x/bin/todo/dist/todo.apk to /Users/x/xx/xxx/sootOutput/merged.apk
09/28/2021 - 11:12:58 AMT-Log> successful!


09/28/2021 - 11:12:58 AMT-Log> Stored in: /Users/x/xx/xxx/output/239d512be3997e73bef660e50b86db429031087b


09/28/2021 - 11:12:58 AMT-Log> AMT finished! (62s)
```
and the apks:
[todo-HelloWorld.zip](https://github.com/FoelliX/AMT/files/7240759/todo-HelloWorld.zip)

So, How to solve this error? Thanks, best regards.

**Comment by hwangjr** [comment]
I check the #3, and found:
```
		final List<String> excludeList = new ArrayList<>();
		excludeList
				.addAll(Arrays.asList(new String[] { Data.getInstance().getPackageMap().get(filePath) + ".BuildConfig",
						Data.getInstance().getPackageMap().get(filePath) + ".R",
						Data.getInstance().getPackageMap().get(filePath) + ".R$*" }));
		if (flag != FLAG_MERGE) {
			excludeList.addAll(Arrays.asList(new String[] { "android.support.*", "com.google.*", "androidx.*" }));
		}
		Log.log("Excluding: " + excludeList.toString(), Log.LOG_LEVEL_DETAILED);
		Options.v().set_exclude(excludeList);
```

**Comment by hwangjr** [comment]
Here is the app crash log:
```

    
    --------- beginning of crash
2021-09-28 11:40:09.292 12636-12636/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.neomsoft.todo, PID: 12636
    java.lang.VerifyError: Rejecting class io.github.neomsoft.todo.ui.activities.MainActivity because it failed compile-time verification (declaration of 'io.github.neomsoft.todo.ui.activities.MainActivity' appears in /data/app/io.github.neomsoft.todo-1/base.apk)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2455)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2614)
        at android.app.ActivityThread.access$1100(ActivityThread.java:165)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1482)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:179)
        at android.app.ActivityThread.main(ActivityThread.java:5739)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
        at io.swe.android.xharlay.XharlayBridge.main(XharlayBridge.java:107)
2021-09-28 11:40:09.295 1502-3294/? W/ActivityManager:   Force finishing activity io.github.neomsoft.todo/.ui.activities.MainActivity
```

**Comment by FoelliX** [comment]
Hi hwangjr!

> So, How to solve this error?

> and the package "android.support.", "com.google.", "androidx.*" will not be merged? so how to merge this system lib?

Sorry, I currently do not have a solution that solves this error and no answer on how to merge these parts (still no deeper insights on what causes the error). Might be related to a Soot internal error. Thus, I just tried it with the newest Soot version, however, it still shows the same errors.

> Here is the app crash log: [...]

The merged app will not be runnable for two reasons:
1. the classes that could not be written to the APK are missing,
2. the Anroid manifests cannot be merged successfully since there are some layout variables missing - no layout files or similar are currently merged by AMT.

The latter is also the cause for:
> 09/28/2021 - 11:12:57 AMT-Log> File could not be moved from /Users/x/bin/todo/dist/todo.apk to /Users/x/xx/xxx/sootOutput/merged.apk

You can get more debug information if you add the launch parameter "-d detailed/debug" (e.g. `java -jar AMT.jar -d detailed todo.apk HelloWorld.apk`)

The output app should still be analyzable even though it is not runnable.

Cheers,
FoelliX

**Comment by hwangjr** [comment]
Thanks for your reply, I already update the dependencies(pom.xml):
```
	<dependencies>
		<!-- https://sable.github.io/soot/ -->
		<dependency>
			<groupId>org.soot-oss</groupId>
			<artifactId>soot</artifactId>
			<version>4.2.1</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/net.dongliu/apk-parser -->
		<dependency>
			<groupId>net.dongliu</groupId>
			<artifactId>apk-parser</artifactId>
			<version>2.6.10</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/de.foellix/AQL-System -->
		<dependency>
			<groupId>de.foellix</groupId>
			<artifactId>AQL-System</artifactId>
			<version>1.2.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>5.6.3</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
```
Here is the `java -jar AMT.jar -d detailed todo.apk HelloWorld.apk` log:
```
java -jar AMT.jar -d detailed todo.apk HelloWorld.apk
09/28/2021 - 03:17:43 AMT-Log> AMT started! (Merging 2 apps)
	1. /Users/x/xx/xxx/todo.apk
	2. /Users/x/xx/xxx/HelloWorld.apk


09/28/2021 - 03:17:43 AMT-Log> *** Step 1/5: Parsing Manifest ***
09/28/2021 - 03:17:43 AMT-Log> Package identified: io.github.neomsoft.todo
09/28/2021 - 03:17:43 AMT-Log> Launcher-Activity found: io.github.neomsoft.todo.ui.activities.MainActivity (/Users/x/xx/xxx/todo.apk)
09/28/2021 - 03:17:43 AMT-Log> Launcher-Activity selected: io.github.neomsoft.todo.ui.activities.MainActivity (/Users/x/xx/xxx/todo.apk)
09/28/2021 - 03:17:43 AMT-Log> Package identified: com.test
09/28/2021 - 03:17:43 AMT-Log> Launcher-Activity found: com.test.MainActivity (/Users/x/xx/xxx/HelloWorld.apk)
09/28/2021 - 03:17:43 AMT-Log> successful!


09/28/2021 - 03:17:43 AMT-Log> *** Step 2/5: Parsing Apps ***
09/28/2021 - 03:17:43 AMT-Log> Running Soot: /Users/x/xx/xxx/HelloWorld.apk (Mode: 1)
09/28/2021 - 03:17:43 AMT-Log> Excluding: [com.test.BuildConfig, com.test.R, com.test.R$*, android.support.*, com.google.*, androidx.*]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
09/28/2021 - 03:17:49 AMT-Log> Soot: done!
09/28/2021 - 03:17:49 AMT-Log> successful!


09/28/2021 - 03:17:49 AMT-Log> *** Step 3/5: Instrumenting Classes ***
09/28/2021 - 03:17:49 AMT-Log> Running Soot: /Users/x/xx/xxx/todo.apk (Mode: 2)
09/28/2021 - 03:17:49 AMT-Log> Excluding: [io.github.neomsoft.todo.BuildConfig, io.github.neomsoft.todo.R, io.github.neomsoft.todo.R$*]
09/28/2021 - 03:17:52 AMT-Log> Method <io.github.neomsoft.todo.ui.activities.MainActivity: void onCreate(android.os.Bundle)> modified to <io.github.neomsoft.todo.ui.activities.MainActivity: void OriginalonCreate(android.os.Bundle)>
09/28/2021 - 03:17:52 AMT-Log> Applying modifier on: onCreate
09/28/2021 - 03:17:52 AMT-Log> Create lifecycle method for: onCreate
09/28/2021 - 03:17:52 AMT-Log> successful!


09/28/2021 - 03:17:52 AMT-Log> *** Step 4/5: Building Merged App ***
09/28/2021 - 03:17:55 AMT-Log> Writing APK!
09/28/2021 - 03:17:57 AMT-Log> Soot: done!
09/28/2021 - 03:17:57 AMT-Log> successful!


09/28/2021 - 03:17:57 AMT-Log> *** Step 5/5: Run Apktool (Merge Manifests) ***
09/28/2021 - 03:17:57 AMT-Log> Executing Apktool: java -jar apktool.jar -f d todo.apk
09/28/2021 - 03:17:58 AMT-Log> I: Using Apktool 2.6.1-9bdf38-SNAPSHOT on todo.apk
09/28/2021 - 03:17:58 AMT-Log> I: Loading resource table...
09/28/2021 - 03:17:58 AMT-Log> I: Decoding AndroidManifest.xml with resources...
09/28/2021 - 03:17:58 AMT-Log> I: Loading resource table from file: /Users/x/Library/apktool/framework/1.apk
09/28/2021 - 03:17:59 AMT-Log> I: Regular manifest package...
09/28/2021 - 03:17:59 AMT-Log> I: Decoding file-resources...
09/28/2021 - 03:18:00 AMT-Log> I: Decoding values */* XMLs...
09/28/2021 - 03:18:00 AMT-Log> I: Baksmaling classes.dex...
09/28/2021 - 03:18:01 AMT-Log> I: Copying assets and libs...
09/28/2021 - 03:18:01 AMT-Log> I: Copying unknown files...
09/28/2021 - 03:18:01 AMT-Log> I: Copying original files...
09/28/2021 - 03:18:01 AMT-Log> Activity added to manifest: com.test.MainActivity
09/28/2021 - 03:18:01 AMT-Log> Executing Apktool: java -jar apktool.jar b todo
09/28/2021 - 03:18:02 AMT-Log> I: Using Apktool 2.6.1-9bdf38-SNAPSHOT
09/28/2021 - 03:18:02 AMT-Log> I: Checking whether sources has changed...
09/28/2021 - 03:18:02 AMT-Log> I: Smaling smali folder into classes.dex...
09/28/2021 - 03:18:06 AMT-Log> I: Checking whether resources has changed...
09/28/2021 - 03:18:06 AMT-Log> I: Building resources...
09/28/2021 - 03:18:07 AMT-Log> W: /Users/x/bin/todo/AndroidManifest.xml:30: error: Error: String types not allowed (at 'theme' with value 'resourceId:0x7f1101d2').
09/28/2021 - 03:18:07 AMT-Log> W:
09/28/2021 - 03:18:07 AMT-Log> brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/2s/xw9y8hd17g12wg9jsnl1l5880000gn/T/brut_util_Jar_21697299175643234487267245365232916308.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 29, --version-code, 20, --version-name, 2.3, --no-version-vectors, -F, /var/folders/2s/xw9y8hd17g12wg9jsnl1l5880000gn/T/APKTOOL2430101632808594132.tmp, -e, /var/folders/2s/xw9y8hd17g12wg9jsnl1l5880000gn/T/APKTOOL13051604768176684922.tmp, -0, arsc, -I, /Users/x/Library/apktool/framework/1.apk, -S, /Users/x/bin/todo/res, -M, /Users/x/bin/todo/AndroidManifest.xml]
09/28/2021 - 03:18:07 AMT-Log> File could not be moved from /Users/x/bin/todo/dist/todo.apk to /Users/x/xx/xxx/sootOutput/merged.apk
09/28/2021 - 03:18:07 AMT-Log> successful!


09/28/2021 - 03:18:07 AMT-Log> Stored in: /Users/x/xx/xxx/output/239d512be3997e73bef660e50b86db429031087b


09/28/2021 - 03:18:07 AMT-Log> AMT finished! (24s)
```

**Comment by FoelliX** [comment]
Hi again!

Your log matches what I got with up-to-date Soot.

Anyway the manifests still are not merged since the other resource XML files are not touched at all by AMT, yet:
> `09/28/2021 - 03:18:07 AMT-Log> W: /Users/x/bin/todo/AndroidManifest.xml:30: error: Error: String types not allowed (at 'theme' with value 'resourceId:0x7f1101d2').`
So the following is actually not true:
> `09/28/2021 - 03:18:07 AMT-Log> successful!`

However, the code is merged(!) but does not include the excluded library parts of the second APK:
> `09/28/2021 - 09:40:13 AMT-Log> Excluding: [com.test.BuildConfig, com.test.R, com.test.R$*, android.support.*, com.google.*, androidx.*, kotlin.*]`

Cheers,
FoelliX

**Comment by hwangjr** [comment]
I have decompile the HelloWorld.apk, and found the resource id is theme, it seems the theme not merge to the new apk. any idea about how to solve this issue?
![image](https://user-images.githubusercontent.com/2850206/135047169-ff639cc5-8f94-44f1-b767-43302af13fb4.png)

**Comment by hwangjr** [comment]
it seems that merge two apks is a little complex, like theme merge, system lib different version merge, kotlin different version merge, duplicate res id merge, etc...

**Comment by hwangjr** [comment]
okay, thanks a lot for you reply.
