### ISSUE TITLE
Error when rebuilding Step 4/5: Building Merged App ***

### ISSUE THREAD

**Issue by vietnq308** [FoelliX/AMT#6]
i had run code and when it rebuild, i have an error !

My properties
```
androidPlatforms=/Users/nguyenviet/Library/Android/sdk/platforms
apktoolPath=/opt/homebrew/bin/apktool
apktoolJar=/Users/nguyenviet/Tools/apktool_2.9.3.jar
aqlQuery=Flows IN App('%APP_APK%') USES 'IccTA' ?
comparisonAqlQuery=Flows IN App('%APP_APK%' | 'COMBINE') USES 'IccTA' ?
outputFolder=/Users/nguyenviet/Tools/Android-Merge-Tool
defaultExcludes=android.support.*, androidx.*, kotlin.*
```

LOG:
```
03/12/2024 - 01:30:55 AMT-Log> Create lifecycle method for: onStop
03/12/2024 - 01:30:55 AMT-Log> Create lifecycle method for: onRestart
03/12/2024 - 01:30:55 AMT-Log> successful!


03/12/2024 - 01:30:55 AMT-Log> *** Step 4/5: Building Merged App ***
Exception in thread "main" Exception in thread "Thread-19" soot.jimple.toolkits.typing.integer.InternalTypingException: Unexpected type [0..1] (Integer1Type)
	at soot.jimple.toolkits.typing.integer.ClassHierarchy.typeNode(ClassHierarchy.java:155)
	at soot.jimple.toolkits.typing.integer.TypeResolver.typeVariable(TypeResolver.java:121)
	at soot.jimple.toolkits.typing.integer.ConstraintCollector.caseAssignStmt(ConstraintCollector.java:406)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:242)
	at soot.jimple.toolkits.typing.integer.ConstraintCollector.collect(ConstraintCollector.java:104)
	at soot.jimple.toolkits.typing.integer.TypeResolver.collect_constraints_1(TypeResolver.java:209)
	at soot.jimple.toolkits.typing.integer.TypeResolver.resolve_step_1(TypeResolver.java:178)
	at soot.jimple.toolkits.typing.integer.TypeResolver.resolve(TypeResolver.java:147)
	at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:178)
	at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:121)
	at soot.BodyTransformer.transform(BodyTransformer.java:55)
	at soot.BodyTransformer.transform(BodyTransformer.java:59)
	at soot.dexpler.DexBody.jimplify(DexBody.java:769)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:120)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
	at soot.PackManager$1.run(PackManager.java:1279)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
soot.jimple.toolkits.typing.integer.InternalTypingException: Unexpected type [0..1] (Integer1Type)
	at soot.jimple.toolkits.typing.integer.ClassHierarchy.typeNode(ClassHierarchy.java:155)
	at soot.jimple.toolkits.typing.integer.TypeResolver.typeVariable(TypeResolver.java:121)
	at soot.jimple.toolkits.typing.integer.ConstraintCollector.caseAssignStmt(ConstraintCollector.java:406)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:242)
	at soot.jimple.toolkits.typing.integer.ConstraintCollector.collect(ConstraintCollector.java:104)
	at soot.jimple.toolkits.typing.integer.TypeResolver.collect_constraints_1(TypeResolver.java:209)
	at soot.jimple.toolkits.typing.integer.TypeResolver.resolve_step_1(TypeResolver.java:178)
	at soot.jimple.toolkits.typing.integer.TypeResolver.resolve(TypeResolver.java:147)
	at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:178)
	at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:121)
	at soot.BodyTransformer.transform(BodyTransformer.java:55)
	at soot.BodyTransformer.transform(BodyTransformer.java:59)
	at soot.dexpler.DexBody.jimplify(DexBody.java:769)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:120)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
	at soot.PackManager$1.run(PackManager.java:1279)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by FoelliX** [comment]
Hi vietnq308,

have not seen this error before. From the log I can only guess that it is a Soot internal error. To test, I first need all information to reproduce the error. Can you also provide the apps you attempted to merge and the complete command you used to run AMT?

Cheers
FoelliX

**Comment by vietnq308** [comment]
i was solve this by run it again, so weird
